version: "2"
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx_service
    ports:
      - "8080:80"
    networks:
      - backend

  auth:
    build:
      context: ./auth
    container_name: auth_service
    networks:
      - backend
    command: auth

  flights:
    build:
      context: ./flights
    container_name: flights_service
    volumes:
      - "./flights/src:/code"
    networks:
      - backend
    command: python run.py

  sale:
    build:
      context: ./sale
    container_name: sale
    networks:
      - backend
    command: python run.py
    depends_on:
      - auth

networks:
  backend:
